export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const FETCH_USER_TODOS_REQUEST = 'FETCH_USER_TODOS_REQUEST'
export const FETCH_USER_TODOS_SUCCESS = 'FETCH_USER_TODOS_SUCCESS'
export const FETCH_USER_TODOS_FAILURE = 'FETCH_USER_TODOS_FAILURE'
